import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import type { VitalsDB } from '../db/database';
import { BASELINE_SETTINGS, KNOWN_FIXES, type PrescriptionTemplate } from './known-fixes';

export interface Prescription {
  metric: string;
  metricLabel: string;
  currentValue: number;
  threshold: number;
  severity: 'critical' | 'warning';
  fix: PrescriptionTemplate;
}

export interface ApplyResult {
  settingsWritten: boolean;
  settingsPath: string;
  claudeMdWritten: boolean;
  claudeMdPath: string;
  envVarsCount: number;
  claudeMdRulesCount: number;
  settingsCount: number;
}

const PRESCRIPTION_START = '<!-- claude-vitals prescriptions -->';
const PRESCRIPTION_END = '<!-- end claude-vitals prescriptions -->';

export class Prescriber {
  private db: VitalsDB;

  constructor(db: VitalsDB) {
    this.db = db;
  }

  diagnose(): Prescription[] {
    const prescriptions: Prescription[] = [];

    for (const fix of KNOWN_FIXES) {
      const latest = this.db.getLatestMetric(fix.metric);
      if (!latest) continue;

      // Also get 7-day average for stability
      const rows = this.db.getDailyMetrics(fix.metric, 7);
      if (rows.length === 0) continue;
      const avg = rows.reduce((s, r) => s + r.value, 0) / rows.length;

      const isCritical = this.isBeyondThreshold(avg, fix.criticalThreshold, fix.direction);
      const isWarning = this.isBeyondThreshold(avg, fix.warningThreshold, fix.direction);

      if (isCritical || isWarning) {
        for (const template of fix.prescriptions) {
          prescriptions.push({
            metric: fix.metric,
            metricLabel: fix.label,
            currentValue: Math.round(avg * 100) / 100,
            threshold: isCritical ? fix.criticalThreshold : fix.warningThreshold,
            severity: isCritical ? 'critical' : 'warning',
            fix: template,
          });
        }
      }
    }

    return prescriptions;
  }

  getBaselineRecommendations(): PrescriptionTemplate[] {
    return BASELINE_SETTINGS;
  }

  generateSettingsJson(prescriptions: Prescription[]): Record<string, unknown> {
    const settings: Record<string, unknown> = {};
    const env: Record<string, string> = {};
    const permissions: string[] = [];

    for (const p of prescriptions) {
      if (p.fix.type === 'env_var') {
        env[p.fix.key] = String(p.fix.value);
      } else if (p.fix.type === 'settings_json') {
        settings[p.fix.key] = p.fix.value;
      } else if (p.fix.type === 'permissions') {
        const vals = String(p.fix.value)
          .split(',')
          .map((v) => v.trim());
        for (const v of vals) {
          if (!permissions.includes(v)) permissions.push(v);
        }
      }
    }

    if (Object.keys(env).length > 0) {
      settings.env = env;
    }

    if (permissions.length > 0) {
      settings.permissions = { allow: permissions };
    }

    return settings;
  }

  generateClaudeMdBlock(prescriptions: Prescription[]): string {
    const claudeMdFixes = prescriptions.filter((p) => p.fix.type === 'claude_md');
    if (claudeMdFixes.length === 0) return '';

    const date = new Date().toISOString().slice(0, 10);
    const lines: string[] = [];

    lines.push(PRESCRIPTION_START);
    lines.push(`## Quality Rules (auto-generated by claude-vitals on ${date})`);
    lines.push('');
    lines.push(
      'These rules were prescribed based on measured quality regressions in your session logs.',
    );
    lines.push('');

    // Deduplicate by key
    const seen = new Set<string>();
    for (const p of claudeMdFixes) {
      if (seen.has(p.fix.key)) continue;
      seen.add(p.fix.key);
      lines.push(`### ${p.fix.description}`);
      lines.push('');
      lines.push(String(p.fix.value));
      lines.push('');
    }

    lines.push(PRESCRIPTION_END);
    return lines.join('\n');
  }

  generateEnvExports(prescriptions: Prescription[]): string {
    const envFixes = prescriptions.filter((p) => p.fix.type === 'env_var');
    if (envFixes.length === 0) return '';

    const seen = new Set<string>();
    const lines: string[] = [];
    for (const p of envFixes) {
      if (seen.has(p.fix.key)) continue;
      seen.add(p.fix.key);
      lines.push(`export ${p.fix.key}="${p.fix.value}"`);
    }
    return lines.join('\n');
  }

  apply(
    prescriptions: Prescription[],
    options: { target?: 'global' | 'project' } = {},
  ): ApplyResult {
    const target = options.target || 'global';
    const baseDir =
      target === 'global'
        ? path.join(os.homedir(), '.claude')
        : path.join(process.cwd(), '.claude');

    // Ensure directory exists
    if (!fs.existsSync(baseDir)) {
      fs.mkdirSync(baseDir, { recursive: true });
    }

    const result: ApplyResult = {
      settingsWritten: false,
      settingsPath: path.join(
        baseDir,
        target === 'global' ? 'settings.json' : 'settings.local.json',
      ),
      claudeMdWritten: false,
      claudeMdPath:
        target === 'global'
          ? path.join(baseDir, 'CLAUDE.md')
          : path.join(process.cwd(), 'CLAUDE.md'),
      envVarsCount: 0,
      claudeMdRulesCount: 0,
      settingsCount: 0,
    };

    // Apply settings.json (deep merge)
    const settingsPrescriptions = prescriptions.filter(
      (p) =>
        p.fix.type === 'env_var' || p.fix.type === 'settings_json' || p.fix.type === 'permissions',
    );
    if (settingsPrescriptions.length > 0) {
      const newSettings = this.generateSettingsJson(prescriptions);
      result.settingsWritten = this.mergeSettingsFile(result.settingsPath, newSettings);
      result.envVarsCount = new Set(
        prescriptions.filter((p) => p.fix.type === 'env_var').map((p) => p.fix.key),
      ).size;
      result.settingsCount = new Set(
        prescriptions.filter((p) => p.fix.type === 'settings_json').map((p) => p.fix.key),
      ).size;
    }

    // Apply CLAUDE.md additions
    const claudeMdBlock = this.generateClaudeMdBlock(prescriptions);
    if (claudeMdBlock) {
      result.claudeMdWritten = this.mergeClaudeMd(result.claudeMdPath, claudeMdBlock);
      result.claudeMdRulesCount = new Set(
        prescriptions.filter((p) => p.fix.type === 'claude_md').map((p) => p.fix.key),
      ).size;
    }

    return result;
  }

  private mergeSettingsFile(filePath: string, newSettings: Record<string, unknown>): boolean {
    let existing: Record<string, unknown> = {};

    if (fs.existsSync(filePath)) {
      try {
        existing = JSON.parse(fs.readFileSync(filePath, 'utf-8'));
      } catch {
        existing = {};
      }
    }

    // Deep merge env vars
    if (newSettings.env) {
      if (!existing.env || typeof existing.env !== 'object') {
        existing.env = {};
      }
      Object.assign(existing.env as Record<string, unknown>, newSettings.env);
      delete newSettings.env;
    }

    // Merge permissions (union of allow arrays)
    if (newSettings.permissions) {
      const newPerms = newSettings.permissions as { allow?: string[] };
      if (!existing.permissions || typeof existing.permissions !== 'object') {
        existing.permissions = { allow: [] };
      }
      const existingPerms = existing.permissions as { allow?: string[] };
      if (!existingPerms.allow) existingPerms.allow = [];
      for (const p of newPerms.allow || []) {
        if (!existingPerms.allow.includes(p)) {
          existingPerms.allow.push(p);
        }
      }
      delete newSettings.permissions;
    }

    // Merge top-level settings
    Object.assign(existing, newSettings);

    fs.writeFileSync(filePath, `${JSON.stringify(existing, null, 2)}\n`, 'utf-8');
    return true;
  }

  private mergeClaudeMd(filePath: string, block: string): boolean {
    let content = '';

    if (fs.existsSync(filePath)) {
      content = fs.readFileSync(filePath, 'utf-8');
    }

    // Replace existing prescription block if present
    const startIdx = content.indexOf(PRESCRIPTION_START);
    const endIdx = content.indexOf(PRESCRIPTION_END);

    if (startIdx !== -1 && endIdx !== -1) {
      content =
        content.slice(0, startIdx) + block + content.slice(endIdx + PRESCRIPTION_END.length);
    } else {
      // Append
      if (content.length > 0 && !content.endsWith('\n')) {
        content += '\n';
      }
      content += `\n${block}\n`;
    }

    fs.writeFileSync(filePath, content, 'utf-8');
    return true;
  }

  private isBeyondThreshold(
    value: number,
    threshold: number,
    direction: 'above' | 'below',
  ): boolean {
    if (direction === 'above') return value > threshold;
    return value < threshold;
  }
}
