import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import type { VitalsDB } from '../db/database';
import { CODEX_BASELINE, CODEX_KNOWN_FIXES } from './codex-known-fixes';
import { BASELINE_SETTINGS, KNOWN_FIXES, type PrescriptionTemplate } from './known-fixes';

export interface Prescription {
  metric: string;
  metricLabel: string;
  currentValue: number;
  threshold: number;
  severity: 'critical' | 'warning';
  fix: PrescriptionTemplate;
}

export interface ApplyResult {
  settingsWritten: boolean;
  settingsPath: string;
  claudeMdWritten: boolean;
  claudeMdPath: string;
  envVarsCount: number;
  claudeMdRulesCount: number;
  settingsCount: number;
}

export interface CodexApplyResult {
  rulesWritten: string[];
  configTomlWritten: boolean;
  configTomlPath: string;
  agentsMdWritten: boolean;
  agentsMdPath: string;
  agentsMdRulesCount: number;
}

const PRESCRIPTION_START = '<!-- agent-vitals prescriptions -->';
const PRESCRIPTION_END = '<!-- end agent-vitals prescriptions -->';
const AGENTS_MD_START = '<!-- agent-vitals codex prescriptions -->';
const AGENTS_MD_END = '<!-- end agent-vitals codex prescriptions -->';
const CODEX_TOML_MANAGED_START = '# agent-vitals managed start';
const CODEX_TOML_MANAGED_END = '# agent-vitals managed end';

export class Prescriber {
  private db: VitalsDB;

  constructor(db: VitalsDB) {
    this.db = db;
  }

  diagnose(provider: string = '_all'): Prescription[] {
    const prescriptions: Prescription[] = [];
    const providers = this.db.getProvidersInSessions();
    const scope =
      provider === 'codex'
        ? 'codex'
        : provider === 'claude'
          ? 'claude'
          : providers.includes('claude')
            ? 'claude'
            : providers.includes('codex')
              ? 'codex'
              : '_all';
    if (scope === 'claude' && !providers.includes('claude')) return prescriptions;
    if (scope === 'codex' && !providers.includes('codex')) return prescriptions;
    const fixes = scope === 'codex' ? CODEX_KNOWN_FIXES : KNOWN_FIXES;

    for (const fix of fixes) {
      const latest = this.db.getLatestMetric(fix.metric, scope);
      if (!latest) continue;

      // Also get 7-day average for stability
      const rows = this.db.getDailyMetrics(fix.metric, 7, undefined, undefined, scope);
      if (rows.length === 0) continue;
      const avg = rows.reduce((s, r) => s + r.value, 0) / rows.length;

      const isCritical = this.isBeyondThreshold(avg, fix.criticalThreshold, fix.direction);
      const isWarning = this.isBeyondThreshold(avg, fix.warningThreshold, fix.direction);

      if (isCritical || isWarning) {
        for (const template of fix.prescriptions) {
          prescriptions.push({
            metric: fix.metric,
            metricLabel: fix.label,
            currentValue: Math.round(avg * 100) / 100,
            threshold: isCritical ? fix.criticalThreshold : fix.warningThreshold,
            severity: isCritical ? 'critical' : 'warning',
            fix: template,
          });
        }
      }
    }

    return prescriptions;
  }

  getBaselineRecommendations(): PrescriptionTemplate[] {
    return BASELINE_SETTINGS;
  }

  getCodexBaselineRecommendations(): PrescriptionTemplate[] {
    return CODEX_BASELINE;
  }

  generateSettingsJson(prescriptions: Prescription[]): Record<string, unknown> {
    const settings: Record<string, unknown> = {};
    const env: Record<string, string> = {};
    const permissions: string[] = [];

    for (const p of prescriptions) {
      if (p.fix.type === 'env_var') {
        env[p.fix.key] = String(p.fix.value);
      } else if (p.fix.type === 'settings_json') {
        settings[p.fix.key] = p.fix.value;
      } else if (p.fix.type === 'permissions') {
        const vals = String(p.fix.value)
          .split(',')
          .map((v) => v.trim());
        for (const v of vals) {
          if (!permissions.includes(v)) permissions.push(v);
        }
      }
    }

    if (Object.keys(env).length > 0) {
      settings.env = env;
    }

    if (permissions.length > 0) {
      settings.permissions = { allow: permissions };
    }

    return settings;
  }

  generateClaudeMdBlock(prescriptions: Prescription[]): string {
    const claudeMdFixes = prescriptions.filter((p) => p.fix.type === 'claude_md');
    if (claudeMdFixes.length === 0) return '';

    const date = new Date().toISOString().slice(0, 10);
    const lines: string[] = [];

    lines.push(PRESCRIPTION_START);
    lines.push(`## Quality Rules (auto-generated by agent-vitals on ${date})`);
    lines.push('');
    lines.push(
      'These rules were prescribed based on measured quality regressions in your session logs.',
    );
    lines.push('');

    // Deduplicate by key
    const seen = new Set<string>();
    for (const p of claudeMdFixes) {
      if (seen.has(p.fix.key)) continue;
      seen.add(p.fix.key);
      lines.push(`### ${p.fix.description}`);
      lines.push('');
      lines.push(String(p.fix.value));
      lines.push('');
    }

    lines.push(PRESCRIPTION_END);
    return lines.join('\n');
  }

  generateEnvExports(prescriptions: Prescription[]): string {
    const envFixes = prescriptions.filter((p) => p.fix.type === 'env_var');
    if (envFixes.length === 0) return '';

    const seen = new Set<string>();
    const lines: string[] = [];
    for (const p of envFixes) {
      if (seen.has(p.fix.key)) continue;
      seen.add(p.fix.key);
      lines.push(`export ${p.fix.key}="${p.fix.value}"`);
    }
    return lines.join('\n');
  }

  apply(
    prescriptions: Prescription[],
    options: { target?: 'global' | 'project' } = {},
  ): ApplyResult {
    const target = options.target || 'global';
    const baseDir =
      target === 'global'
        ? path.join(os.homedir(), '.claude')
        : path.join(process.cwd(), '.claude');

    // Ensure directory exists
    if (!fs.existsSync(baseDir)) {
      fs.mkdirSync(baseDir, { recursive: true });
    }

    const result: ApplyResult = {
      settingsWritten: false,
      settingsPath: path.join(
        baseDir,
        target === 'global' ? 'settings.json' : 'settings.local.json',
      ),
      claudeMdWritten: false,
      claudeMdPath:
        target === 'global'
          ? path.join(baseDir, 'CLAUDE.md')
          : path.join(process.cwd(), 'CLAUDE.md'),
      envVarsCount: 0,
      claudeMdRulesCount: 0,
      settingsCount: 0,
    };

    // Apply settings.json (deep merge)
    const settingsPrescriptions = prescriptions.filter(
      (p) =>
        p.fix.type === 'env_var' || p.fix.type === 'settings_json' || p.fix.type === 'permissions',
    );
    if (settingsPrescriptions.length > 0) {
      const newSettings = this.generateSettingsJson(prescriptions);
      result.settingsWritten = this.mergeSettingsFile(result.settingsPath, newSettings);
      result.envVarsCount = new Set(
        prescriptions.filter((p) => p.fix.type === 'env_var').map((p) => p.fix.key),
      ).size;
      result.settingsCount = new Set(
        prescriptions.filter((p) => p.fix.type === 'settings_json').map((p) => p.fix.key),
      ).size;
    }

    // Apply CLAUDE.md additions
    const claudeMdBlock = this.generateClaudeMdBlock(prescriptions);
    if (claudeMdBlock) {
      result.claudeMdWritten = this.mergeClaudeMd(result.claudeMdPath, claudeMdBlock);
      result.claudeMdRulesCount = new Set(
        prescriptions.filter((p) => p.fix.type === 'claude_md').map((p) => p.fix.key),
      ).size;
    }

    return result;
  }

  applyCodex(
    prescriptions: Prescription[],
    options: { target?: 'global' | 'project' } = {},
  ): CodexApplyResult {
    const target = options.target || 'global';
    const configTomlPath = path.join(os.homedir(), '.codex', 'config.toml');
    const agentsMdPath = path.join(process.cwd(), 'AGENTS.md');

    const result: CodexApplyResult = {
      rulesWritten: [],
      configTomlWritten: false,
      configTomlPath,
      agentsMdWritten: false,
      agentsMdPath,
      agentsMdRulesCount: 0,
    };

    const projectPs = prescriptions.filter((p) => p.fix.type === 'project_instructions');
    if (projectPs.length > 0) {
      const count = this.writeAgentsMd(agentsMdPath, projectPs);
      result.agentsMdWritten = count > 0;
      result.agentsMdRulesCount = count;
    }

    if (target === 'project') {
      return result;
    }

    const rulesPs = prescriptions.filter((p) => p.fix.type === 'codex_rules');
    for (const p of rulesPs) {
      const absPath = this.writeCodexRule(p.fix);
      if (!result.rulesWritten.includes(absPath)) {
        result.rulesWritten.push(absPath);
      }
    }

    const configPs = prescriptions.filter((p) => p.fix.type === 'codex_config_toml');
    if (configPs.length > 0) {
      result.configTomlWritten = this.writeCodexConfigToml(configTomlPath, configPs);
    }

    return result;
  }

  private writeCodexRule(fix: PrescriptionTemplate): string {
    const absPath = fix.key.startsWith('~') ? path.join(os.homedir(), fix.key.slice(1)) : fix.key;
    const dir = path.dirname(absPath);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    const body = String(fix.value).replace(/\n+$/, '');
    const content = `${body}\n`;
    const tmp = `${absPath}.tmp`;
    fs.writeFileSync(tmp, content, 'utf-8');
    fs.renameSync(tmp, absPath);
    return absPath;
  }

  private writeAgentsMd(filePath: string, prescriptions: Prescription[]): number {
    const seen = new Set<string>();
    const entries: Array<{ description: string; value: string }> = [];
    for (const p of prescriptions) {
      const value = String(p.fix.value);
      if (seen.has(value)) continue;
      seen.add(value);
      entries.push({ description: p.fix.description, value });
    }

    if (entries.length === 0) return 0;

    const date = new Date().toISOString().slice(0, 10);
    const lines: string[] = [];
    lines.push(AGENTS_MD_START);
    lines.push(`## Quality Rules (auto-generated by agent-vitals on ${date})`);
    lines.push('');
    lines.push(
      'These rules were prescribed based on measured quality regressions in your session logs.',
    );
    lines.push('');
    for (const e of entries) {
      lines.push(`### ${e.description}`);
      lines.push('');
      lines.push(e.value);
      lines.push('');
    }
    lines.push(AGENTS_MD_END);
    const block = lines.join('\n');

    let content = '';
    if (fs.existsSync(filePath)) {
      content = fs.readFileSync(filePath, 'utf-8');
    }

    const startIdx = content.indexOf(AGENTS_MD_START);
    const endIdx = content.indexOf(AGENTS_MD_END);
    if (startIdx !== -1 && endIdx !== -1 && endIdx > startIdx) {
      content = content.slice(0, startIdx) + block + content.slice(endIdx + AGENTS_MD_END.length);
    } else {
      if (content.length > 0 && !content.endsWith('\n')) {
        content += '\n';
      }
      content += `\n${block}\n`;
    }

    const tmp = `${filePath}.tmp`;
    fs.writeFileSync(tmp, content, 'utf-8');
    fs.renameSync(tmp, filePath);
    return entries.length;
  }

  private writeCodexConfigToml(filePath: string, prescriptions: Prescription[]): boolean {
    const prescribed = new Map<string, string>();
    for (const p of prescriptions) {
      const rhs = String(p.fix.value).trim();
      const match = /^([A-Za-z0-9_.-]+)\s*=\s*(.+)$/.exec(rhs);
      if (!match) continue;
      const key = match[1];
      const val = match[2].trim();
      prescribed.set(key, `${key} = ${val}`);
    }

    if (prescribed.size === 0) return false;

    const dir = path.dirname(filePath);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

    const existing = fs.existsSync(filePath) ? fs.readFileSync(filePath, 'utf-8') : '';
    const origLines = existing.length > 0 ? existing.split('\n') : [];

    const stripped: string[] = [];
    let inManaged = false;
    for (const ln of origLines) {
      const trimmed = ln.trim();
      if (trimmed === CODEX_TOML_MANAGED_START) {
        inManaged = true;
        continue;
      }
      if (trimmed === CODEX_TOML_MANAGED_END) {
        inManaged = false;
        continue;
      }
      if (inManaged) continue;
      stripped.push(ln);
    }

    const tableHeaderRe = /^\s*\[[^\]]+\]\s*$/;
    let firstTableIdx = -1;
    for (let i = 0; i < stripped.length; i++) {
      if (tableHeaderRe.test(stripped[i])) {
        firstTableIdx = i;
        break;
      }
    }
    const rootEnd = firstTableIdx === -1 ? stripped.length : firstTableIdx;
    const rootLines = stripped.slice(0, rootEnd);
    const restLines = stripped.slice(rootEnd);

    const unmatched = new Map(prescribed);
    const rootKeyRe = /^\s*([A-Za-z0-9_.-]+)\s*=/;
    for (let i = 0; i < rootLines.length; i++) {
      const m = rootKeyRe.exec(rootLines[i]);
      if (!m) continue;
      const key = m[1];
      const replacement = unmatched.get(key);
      if (replacement !== undefined) {
        rootLines[i] = replacement;
        unmatched.delete(key);
      }
    }

    const managedLines: string[] = [];
    if (unmatched.size > 0) {
      managedLines.push(CODEX_TOML_MANAGED_START);
      for (const line of unmatched.values()) {
        managedLines.push(line);
      }
      managedLines.push(CODEX_TOML_MANAGED_END);
    }

    const rootTrimmed = [...rootLines];
    while (rootTrimmed.length > 0 && rootTrimmed[rootTrimmed.length - 1].trim() === '') {
      rootTrimmed.pop();
    }
    const restTrimmed = [...restLines];
    while (restTrimmed.length > 0 && restTrimmed[0].trim() === '') {
      restTrimmed.shift();
    }

    const parts: string[] = [];
    if (managedLines.length === 0) {
      if (rootTrimmed.length > 0) parts.push(...rootTrimmed);
      if (restTrimmed.length > 0) {
        if (parts.length > 0) parts.push('');
        parts.push(...restTrimmed);
      }
    } else {
      if (rootTrimmed.length > 0) {
        parts.push(...rootTrimmed);
        parts.push('');
      }
      parts.push(...managedLines);
      if (restTrimmed.length > 0) {
        parts.push('');
        parts.push(...restTrimmed);
      }
    }

    let newContent = parts.join('\n');
    if (!newContent.endsWith('\n')) newContent += '\n';

    const tmp = `${filePath}.tmp`;
    fs.writeFileSync(tmp, newContent, 'utf-8');
    fs.renameSync(tmp, filePath);
    return true;
  }

  private mergeSettingsFile(filePath: string, newSettings: Record<string, unknown>): boolean {
    let existing: Record<string, unknown> = {};

    if (fs.existsSync(filePath)) {
      try {
        existing = JSON.parse(fs.readFileSync(filePath, 'utf-8'));
      } catch {
        existing = {};
      }
    }

    // Deep merge env vars
    if (newSettings.env) {
      if (!existing.env || typeof existing.env !== 'object') {
        existing.env = {};
      }
      Object.assign(existing.env as Record<string, unknown>, newSettings.env);
      delete newSettings.env;
    }

    // Merge permissions (union of allow arrays)
    if (newSettings.permissions) {
      const newPerms = newSettings.permissions as { allow?: string[] };
      if (!existing.permissions || typeof existing.permissions !== 'object') {
        existing.permissions = { allow: [] };
      }
      const existingPerms = existing.permissions as { allow?: string[] };
      if (!existingPerms.allow) existingPerms.allow = [];
      for (const p of newPerms.allow || []) {
        if (!existingPerms.allow.includes(p)) {
          existingPerms.allow.push(p);
        }
      }
      delete newSettings.permissions;
    }

    // Merge top-level settings
    Object.assign(existing, newSettings);

    fs.writeFileSync(filePath, `${JSON.stringify(existing, null, 2)}\n`, 'utf-8');
    return true;
  }

  private mergeClaudeMd(filePath: string, block: string): boolean {
    let content = '';

    if (fs.existsSync(filePath)) {
      content = fs.readFileSync(filePath, 'utf-8');
    }

    // Replace existing prescription block if present
    const startIdx = content.indexOf(PRESCRIPTION_START);
    const endIdx = content.indexOf(PRESCRIPTION_END);

    if (startIdx !== -1 && endIdx !== -1) {
      content =
        content.slice(0, startIdx) + block + content.slice(endIdx + PRESCRIPTION_END.length);
    } else {
      // Append
      if (content.length > 0 && !content.endsWith('\n')) {
        content += '\n';
      }
      content += `\n${block}\n`;
    }

    fs.writeFileSync(filePath, content, 'utf-8');
    return true;
  }

  private isBeyondThreshold(
    value: number,
    threshold: number,
    direction: 'above' | 'below',
  ): boolean {
    if (direction === 'above') return value > threshold;
    return value < threshold;
  }
}
